# Use the official Node.js image
FROM node:16

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Copy .env file
COPY .env ./

# Expose the application port (3000 for internal use)
EXPOSE 3005

# Command to run the application
CMD ["npm", "start"]
