apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: train-system
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "512Mi"
    limits.cpu: "2"
    limits.memory: "1Gi"
